name: Test and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Test app
        run: npm test

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build app
        run: npm run build --ignore-warnings

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.1.0
        with:
          args: --acl public-read --region us-east-2

        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ secrets.AWSS3BUVKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESSKEY }}
          AWS_REGION: 'us-east-2' # Change this to your S3 bucket's region